services:
  unitycatalog:
    image: "clouddataninjas/unitycatalog:latest"
    hostname: unitycatalog
    build:
      context: .      
      dockerfile: docker/DockerfileUC
    container_name: unitycatalog
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./uc/etc/data/:/app/etc/data/
      # updated 
      #   - cli.log4j2.properties AND server.log4j2.properties
      #        rootLogger.level = trace  (instead of info)
      #- ./uc/etc/conf/:/app/etc/conf/      
      #- ./uc/etc/db/:/app/etc/db/
    networks:
      - uc_network
    
  duckdb:
    image: "clouddataninjas/duckdb:latest"
    hostname: duckdb
    build:
      context: .      
      dockerfile: docker/DockerfileDuckDB
    container_name: duckdb        
    volumes:      
      - ./uc/etc/data/:/app/etc/data/      
    depends_on:
      - unitycatalog
    networks:
      - uc_network
  
  jupyter:
    image: "clouddataninjas/jupyter:latest"
    hostname: jupyter
    build:
      context: .      
      dockerfile: docker/DockerfileJupyterIceberg
    container_name: jupyter        
    volumes:      
      - ./uc/etc/data/:/app/etc/data/      
    ports:
      - "8888:8888"
    depends_on:
      - unitycatalog
    networks:
      - uc_network
      
networks:
  uc_network:
    driver: bridge